Importing libraries and functions.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score
from sklearn.linear_model import LogisticRegression

Data import and preparation

In [17]:
df = pd.read_excel(r'C:\Users\mugok\Desktop\Data sets\a_Dataset_CreditScoring.xlsx')
#show count of rows and columns
df.shape

(3000, 30)

In [18]:
df.head()

TARGET    ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1   582         3           3             0         4          0.0   
1       1   662        15           9             0         3          1.0   
2       1   805         0           0             0         1          5.0   
3       1  1175         8           5             0         6          1.0   
4       1  1373         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  TLBalHCPct  \
0                5          117          27  ...          3.0      0.9179   
1                3           14          14  ...          1.0      0.8000   
2                1          354           7  ...          5.0      0.3552   
3               10           16           4  ...          3.0      0.9127   
4                8          130          52  ...          1.0      1.2511   

   TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  TLOpenPct  \
0    0.2083               2             3              7     0.2083   
1    0.0000               0             0              0     1.0000   
2    0.6538               0             1              1     0.7308   
3    0.2500               1             1              1     0.7500   
4    0.0000               0             1              4     0.1429   

   TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0              4             4       0.0000  
1             12             0       1.0000  
2              1             1       0.5263  
3              7             1       1.3333  
4              3             1       0.0000  

[5 rows x 30 columns]

In [19]:
#Dropping customer ID from the dataset
df = df.drop('ID' , axis=1)
df.shape

(3000, 29)

In [20]:
#Look for missing values
df.isnull().sum()


TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [21]:

#Filling missing values with mean
df = df.fillna(df.mean())

In [22]:

#Checking again for missing values.
df.isnull().sum()



TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [23]:
#Count of good loans(0) and bad loans(1)
df['TARGET'].value_counts()

TARGET
0    2500
1     500
Name: count, dtype: int64

In [25]:
#Data summary of 0 and 1
df.groupby('TARGET').mean()

DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
TARGET                                                              
0         1.3224      0.7664        0.1492    2.9424     3.174638   
1         1.9680      1.3100        0.1740    3.9380     2.775459   

        InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  TLCnt12  ...  \
TARGET                                                              ...   
0                3.2896      173.002      11.650   0.2844    1.832  ...   
1                4.8820      155.672      12.992   0.2280    1.768  ...   

        TL50UtilCnt  TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  \
TARGET                                                                    
0          3.986711    0.628177  0.544963          0.6044        0.6624   
1          4.533870    0.748185  0.385173          1.3340        1.5760   

        TLDel60CntAll  TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
TARGET                                                                      
0              2.2236   0.502376          1.180        0.8648     0.556867  
1              4.0140   0.465127          2.554        2.0860     0.600978  

[2 rows x 28 columns]

Train Test Split

In [58]:
x = df.iloc[:,1:29].values
y = df.iloc[:,0].values

In [59]:
#Splitting the dataset in a ratio of 80:20 (Training to test set)
x_train , x_test ,y_train,y_test = train_test_split(x , y , test_size=0.2 ,random_state= 0 )
y_test

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,

In [60]:
#Data normalization
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Risk Model Building

In [61]:
classifier = LogisticRegression()
classifier.fit(x_train , y_train)
y_pred = classifier.predict(x_test)

Model perfomance

In [62]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[482  16]
 [ 88  14]]
0.8266666666666667


Writting Output File

In [63]:
predictions = classifier.predict_proba(x_test)
predictions

#Column 1 (0 = goodloans) , column 2 (1 = bad loans)

array([[0.04043521, 0.95956479],
       [0.93779812, 0.06220188],
       [0.7116222 , 0.2883778 ],
       ...,
       [0.97060955, 0.02939045],
       [0.4548394 , 0.5451606 ],
       [0.86724904, 0.13275096]])

In [67]:
#writting output file
df_prection_proba = pd.DataFrame(predictions , columns=["Prob_0(Good loan)" , "Prob_1(Bad loan)"])
df_prediction_target = pd.DataFrame(classifier.predict(x_test) , columns=["Predicted_target"])
df_test_dataset = pd.DataFrame(y_test , columns=["Actual Outcome"])

dfx = pd.concat([df_test_dataset,df_prection_proba,df_prediction_target ], axis=1)

dfx.to_csv("Ouput.csv" ,sep=',' , encoding='UTF-8' ,index=False)

dfx.head()



Actual Outcome  Prob_0(Good loan)  Prob_1(Bad loan)  Predicted_target
0               1           0.040435          0.959565                 1
1               0           0.937798          0.062202                 0
2               0           0.711622          0.288378                 0
3               0           0.906753          0.093247                 0
4               0           0.877058          0.122942                 0